import React from 'react';
import Heading from "./Heading";
import Section from "./Section";
import { websiteName, websiteUrl, email, address, phone_number } from "../constants";

const RefundPolicy = () => {
    return (
        <Section>
            <div className="container relative z-2">
                <div>
                    <strong>
                        <span style={{ fontSize: 26 }}>
                            <span data-custom-class="title">
                                <bdt className="block-component" />
                                <bdt className="question">RETURN POLICY</bdt>
                                <bdt className="statement-end-if-in-editor" />
                            </span>
                        </span>
                    </strong>
                </div>
                <div>
                    <span style={{ color: "rgb(224, 224, 224)" }}>
                        <strong>
                            <span style={{ fontSize: 15 }}>
                                <span data-custom-class="subtitle">
                                    Last updated <bdt className="question">May 11, 2024</bdt>
                                </span>
                            </span>
                        </strong>
                    </span>
                </div>
                <div>
                    <br />
                </div>
                <div className="MsoNormal" style={{ WebkitTextStrokeWidth: '0px', backgroundAttachment: 'initial !important', backgroundClip: 'initial !important', backgroundImage: 'initial !important', backgroundOrigin: 'initial !important', backgroundPosition: 'initial !important', backgroundRepeat: 'initial !important', backgroundSize: 'initial !important', boxSizing: 'border-box', color: 'rgb(89, 89, 89) !important', fontSize: '14px', fontStyle: 'normal', fontVariantCaps: 'normal', fontVariantLigatures: 'normal', fontWeight: 400, letterSpacing: 'normal', lineHeight: '1.5', orphans: 2, textAlign: 'start', textDecorationColor: 'initial', textDecorationStyle: 'initial', textDecorationThickness: 'initial', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px' }} data-custom-class="body_text"><span style={{ backgroundColor: 'transparent', color: 'rgb(200,200,200)', fontFamily: 'Arial', fontSize: '15px' }}><span style={{ boxSizing: 'border-box', lineHeight: '16.1px' }}>
                    <bdt className="block-component" style={{ backgroundColor: 'transparent', boxSizing: 'border-box', color: 'rgb(89, 89, 89) !important', fontSize: '14px !important' }} />
                </span></span></div>
                <div style={{ WebkitTextStrokeWidth: '0px', backgroundAttachment: 'initial !important', backgroundClip: 'initial !important', backgroundImage: 'initial !important', backgroundOrigin: 'initial !important', backgroundPosition: 'initial !important', backgroundRepeat: 'initial !important', backgroundSize: 'initial !important', boxSizing: 'border-box', color: 'rgb(0, 0, 0) !important', fontSize: '19px !important', fontStyle: 'normal', fontVariantCaps: 'normal', fontVariantLigatures: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textDecorationColor: 'initial', textDecorationStyle: 'initial', textDecorationThickness: 'initial', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px' }} data-custom-class="heading_1"><span style={{ backgroundColor: 'transparent', color: 'rgb(0,0,0)!important', fontSize: '19px' }}><span style={{ boxSizing: 'border-box' }}><strong style={{ backgroundColor: 'transparent', boxSizing: 'border-box', color: 'rgb(0, 0, 0) !important', fontSize: '19px !important', fontWeight: 'bolder' }}>REFUNDS</strong></span></span></div>
                <div style={{ WebkitTextStrokeWidth: '0px', backgroundAttachment: 'initial !important', backgroundClip: 'initial !important', backgroundImage: 'initial !important', backgroundOrigin: 'initial !important', backgroundPosition: 'initial !important', backgroundRepeat: 'initial !important', backgroundSize: 'initial !important', boxSizing: 'border-box', color: 'rgb(108, 119, 148)', fontFamily: 'Roboto', fontSize: '14px', fontStyle: 'normal', fontVariantCaps: 'normal', fontVariantLigatures: 'normal', fontWeight: 400, letterSpacing: 'normal', lineHeight: '1.5', orphans: 2, textAlign: 'start', textDecorationColor: 'initial', textDecorationStyle: 'initial', textDecorationThickness: 'initial', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px' }}>&nbsp;</div>
                <div style={{ WebkitTextStrokeWidth: '0px', backgroundAttachment: 'initial !important', backgroundClip: 'initial !important', backgroundImage: 'initial !important', backgroundOrigin: 'initial !important', backgroundPosition: 'initial !important', backgroundRepeat: 'initial !important', backgroundSize: 'initial !important', boxSizing: 'border-box', color: 'rgb(89, 89, 89) !important', fontSize: '14px', fontStyle: 'normal', fontVariantCaps: 'normal', fontVariantLigatures: 'normal', fontWeight: 400, letterSpacing: 'normal', lineHeight: '1.5', orphans: 2, textAlign: 'start', textDecorationColor: 'initial', textDecorationStyle: 'initial', textDecorationThickness: 'initial', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px' }} data-custom-class="body_text"><span style={{ backgroundColor: 'transparent', color: 'rgb(200,200,200)!important', fontSize: '15px' }}><span style={{ boxSizing: 'border-box' }}>All sales are final and no refund will be issued.<bdt className="block-component" style={{ backgroundColor: 'transparent', boxSizing: 'border-box', color: 'rgb(89, 89, 89) !important', fontSize: '14px !important' }} /></span></span></div>
                <div style={{ WebkitTextStrokeWidth: '0px', backgroundAttachment: 'initial !important', backgroundClip: 'initial !important', backgroundImage: 'initial !important', backgroundOrigin: 'initial !important', backgroundPosition: 'initial !important', backgroundRepeat: 'initial !important', backgroundSize: 'initial !important', boxSizing: 'border-box', color: 'rgb(108, 119, 148)', fontFamily: 'Roboto', fontSize: '14px', fontStyle: 'normal', fontVariantCaps: 'normal', fontVariantLigatures: 'normal', fontWeight: 400, letterSpacing: 'normal', lineHeight: '1.5', orphans: 2, textAlign: 'start', textDecorationColor: 'initial', textDecorationStyle: 'initial', textDecorationThickness: 'initial', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px' }}>&nbsp;</div>
                <div style={{ WebkitTextStrokeWidth: '0px', backgroundAttachment: 'initial !important', backgroundClip: 'initial !important', backgroundImage: 'initial !important', backgroundOrigin: 'initial !important', backgroundPosition: 'initial !important', backgroundRepeat: 'initial !important', backgroundSize: 'initial !important', boxSizing: 'border-box', color: 'rgb(0, 0, 0) !important', fontSize: '19px !important', fontStyle: 'normal', fontVariantCaps: 'normal', fontVariantLigatures: 'normal', fontWeight: 400, letterSpacing: 'normal', lineHeight: '1.5', orphans: 2, textAlign: 'start', textDecorationColor: 'initial', textDecorationStyle: 'initial', textDecorationThickness: 'initial', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px' }} data-custom-class="heading_1"><span style={{ backgroundColor: 'transparent', color: 'rgb(0,0,0)', fontSize: '19px' }}><span style={{ boxSizing: 'border-box' }}><strong style={{ backgroundColor: 'transparent', boxSizing: 'border-box', color: 'rgb(256, 256, 256)', fontSize: '19px !important', fontWeight: 'bolder' }}>QUESTIONS</strong></span></span></div>
                <div style={{ WebkitTextStrokeWidth: '0px', backgroundAttachment: 'initial !important', backgroundClip: 'initial !important', backgroundImage: 'initial !important', backgroundOrigin: 'initial !important', backgroundPosition: 'initial !important', backgroundRepeat: 'initial !important', backgroundSize: 'initial !important', boxSizing: 'border-box', color: 'rgb(108, 119, 148)', fontFamily: 'Roboto', fontSize: '14px', fontStyle: 'normal', fontVariantCaps: 'normal', fontVariantLigatures: 'normal', fontWeight: 400, letterSpacing: 'normal', lineHeight: '1.5', orphans: 2, textAlign: 'start', textDecorationColor: 'initial', textDecorationStyle: 'initial', textDecorationThickness: 'initial', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px' }}>&nbsp;</div>
                <div style={{ WebkitTextStrokeWidth: '0px', backgroundAttachment: 'initial !important', backgroundClip: 'initial !important', backgroundImage: 'initial !important', backgroundOrigin: 'initial !important', backgroundPosition: 'initial !important', backgroundRepeat: 'initial !important', backgroundSize: 'initial !important', boxSizing: 'border-box', color: 'rgb(89, 89, 89) !important', fontSize: '14px', fontStyle: 'normal', fontVariantCaps: 'normal', fontVariantLigatures: 'normal', fontWeight: 400, letterSpacing: 'normal', lineHeight: '1.5', orphans: 2, textAlign: 'start', textDecorationColor: 'initial', textDecorationStyle: 'initial', textDecorationThickness: 'initial', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px' }} data-custom-class="body_text"><span style={{ backgroundColor: 'transparent', color: 'rgb(200,200,200)', fontSize: '15px' }}><span style={{ boxSizing: 'border-box' }}>If you have any questions concerning our return policy, please contact us at : {email}</span></span></div>
                <div style={{ WebkitTextStrokeWidth: '0px', backgroundAttachment: 'initial !important', backgroundClip: 'initial !important', backgroundImage: 'initial !important', backgroundOrigin: 'initial !important', backgroundPosition: 'initial !important', backgroundRepeat: 'initial !important', backgroundSize: 'initial !important', boxSizing: 'border-box', color: 'rgb(89, 89, 89) !important', fontSize: '14px', fontStyle: 'normal', fontVariantCaps: 'normal', fontVariantLigatures: 'normal', fontWeight: 400, letterSpacing: 'normal', lineHeight: '1.5', orphans: 2, textAlign: 'start', textDecorationColor: 'initial', textDecorationStyle: 'initial', textDecorationThickness: 'initial', textIndent: '0px', textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: '0px' }} data-custom-class="body_text">&nbsp;</div>
            </div>
        </Section>
    );
};

export default RefundPolicy;